title: Fettfri.nu
name: Fettfri.nu
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
domain: http://www.fettfri.nu
ogurl: http://fettfri.nu
baseurl: ""
permalink: /:title/
plugins:
- jekyll-redirect-from
