title: Fettfri.nu
name: Fettfri.nu
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
domain: https://fettfri.nu
ogurl: https://fettfri.nu
baseurl: ""
permalink: /:title/
url: https://fettfri.nu
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
